### PR TITLE
Adding database support and creating a GUI for quick lookup.

### PR DESCRIPTION
**Pull request by wlieurance**
I was looking for a way to have quick access to various D&D indices and came across your git page.  It contained a great set of starting points for this project and I used them to load information into a database via python.  From there I created a tkinter GUI (also in python) and loaded information from the indices into it.  This GUI has proven to be quite handy for quick index lookups during games, and it also has the option of opening digital backup scans of game resources to specific pages after they have been identified.

### CODE REVIEW

**Comment by copperdogma** [comment]
Whoa! Nice work! Thank you so much.

**Comment by wlieurance** [comment]
Thanks, I just did another pull request.  This should fix some issues with
the pdf reader being found correctly (such that users can click on the page
number and open a pdf to that page, assuming they have a pdf).  Also added
non-index monster and spell information to the database. Currently that new
data can only be accessed via the sqlite3 command line command (or similar
db reading program), which most users probably won't use, but maybe it can
be built into other things at a later date :/

I wasn't sure of the best practice to document the changes, so put them in
the README.update file.  At some point those should probably be merged into
the main README.md file, but thought it was better to let you edit that
since you are the main author.

Good work on the improved indices. You are correct in that the original
versions super suck.

**Comment by basilforth** [comment]
Forgive the layman's question....

If you have a moment, could you provide some steps for me to install the GUI so I can use your work?

**Comment by wlieurance** [comment]
Sure.
1) Have python3 installed.
2) Have tkinter installed. On windows I think its installed by default with
python 3.
3) Goto your shell (bash on linux, cmd.exe or powershell on windows) and
change your directory to the location of the /utils directory
4) Enter the following command: (linux: python3 ./create_db.py), (windows:
py -3 .\create_db.py)
5) Assuming the process finishes without error, you should now have a
'dmdb.sqlite' file in your /utils folder.
6) run the following command: (linux: python3 ./index_crawler.py),
(windows: py -3 .\index_crawler.py)

This will get the GUI up and running.  Getting the GUI to pop open a pdf to
a selected page requires making sure your pdf paths are in the database
(see examples in the update.sql script).  Once you have the update.sql file
populated you can either rerun create_db.py to create a fresh db or run the
script through the sqlite command line (i.e. 'sqlite3 dmdb.sqlite' and then
'.read update.sql')

Also you need to make sure your pdf reader is is listed in the
pdf_options.json file.  See existing entries for examples.  If you have
adobe reader, you should be able to just replace the path to AcroRd32.exe
in the json file with the path on your specific system. note: until the
next pull request goes through the GUI only reads the first entry in the
json file, so for a hacky fix you can change the order of the two entries
(evince and adobe reader).

Hope that helps!

**Comment by basilforth** [comment]
Thank you very much!  I will give it a try and let you know how it goes!  Thank you both for all your efforts.

**Pull request merged**
